name: sparta-koffer-redhat-operators
on:
  schedule:
    - cron: '0 12 * * TUE'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: rhel
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rake Variables
      run: |
        set -x ; \
          echo "varrundate=$(date +%y%m%d%I%M%S)" >> ${GITHUB_ENV};\
          echo "varveropenshift=$(curl --silent https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | awk '/^Name:/{print $2}')" >> ${GITHUB_ENV};\
         echo;

    - name: Koffer Bundle | Collector Red Hat Operators
      run: |
        set -ex; \
          mkdir -p $(pwd)/bundle; \
          sudo podman run -it --rm --pull always \
                          --env WALLE='true' \
                          --env BUNDLE='true' \
                          --env OPERATORS='cluster-logging,rhsso-operator,servicemeshoperator' \
                          --volume ${HOME}/.docker:/root/.docker:z \
                          --volume $(pwd)/bundle:/root/bundle:z \
                          --privileged --device /dev/fuse \
                      quay.io/cloudctl/koffer:extra bundle --silent --plugin collector-operators; \
          sudo chown -R ec2-user:ec2-user $(pwd)/bundle; \
          sudo chmod -R 0777 $(pwd)/bundle; \
         echo;

    - name: Cradle Bundle | Red Hat Operators
      run: |
        set -ex; \
          podman build \
                 -f ./Dockerfile.operators \
                 -t quay.io/${{ secrets.GIT_PROJECT }}/bundles:redhat-operators \
                 -t quay.io/${{ secrets.GIT_PROJECT }}/bundles:redhat-operators-${{ env.varveropenshift }}; \
          sudo rm -rf $(pwd)/bundle; \
         echo;

    - name: Cradle Push | quay.io/CodeSparta/cradle:redhat-operators
      run: |
        set -x; \
          podman push quay.io/${{ secrets.GIT_PROJECT }}/bundles:redhat-operators;\
          podman push quay.io/${{ secrets.GIT_PROJECT }}/bundles:redhat-operators-${{ env.varveropenshift }};

    - name: Cleanup
      run: |
        set -x; \
          podman image prune --all --force; \
          sudo podman image prune --all --force; \
         echo;
